Repository GatorEducator/gatorgrouper, pull requests merged in 2019-03, with the labels that each got.

#191 Fix master branch failing Travis
  Pipfile.lock
Labels: bug, priority, setup

#185 Increase Code Coverage for All Functions
  gator_grouper/settings.py
  gatorgrouper/tests/test_display.py
  gatorgrouper/tests/test_group_method.py
  gatorgrouper/tests/test_num_group.py
  gatorgrouper/tests/test_read_student_file.py
  gatorgrouper/utils/gatorgrouper.py
  gatorgrouper/utils/read_student_file.py
Labels: enhancement, testing

#189 Moving the issue_template.md to the docs folder to increase code cov
  .github/issue_template.md
  .github/pull_request_template.md
Labels: documentation, setup

#187 Fix incorrect URL in display.py & README.md
  README.md
  gatorgrouper/tests/test_display.py
  gatorgrouper/utils/display.py
Labels: documentation, interface

#155 Project Summary and Logo
  .github/gatorgrouper_logo.svg
  .github/pull_request_template.md
  README.md
Labels: documentation

#175 Created a CONTRIBUTING document to outline project standards for cont…
  CONTRIBUTING.md
Labels: documentation, enhancement

#210 remove pytest-clarity
  Pipfile
  Pipfile.lock
Labels: bug

#211 remove the issue template which is located at the wrong location
  issueTemplate.md
Labels: bug

#208 Adding description to group_random.py Docstrings
  gatorgrouper/utils/group_random.py
Labels: documentation

#195 Renamed functions to avoid confusion with file name
  gatorgrouper/tests/test_absent.py
  gatorgrouper/utils/gatorgrouper.py
  gatorgrouper/utils/remove_absent_students.py
Labels: refactor

#193 Added test cases for Django models
  Pipfile
  gator_grouper/settings.py
  gatorgrouper/tests/test_admin.py
  gatorgrouper/tests/test_models.py
  gatorgrouper/tests/test_urls.py
  gatorgrouper/tests/test_views.py
  pytest.cov
  pytest.ini
Labels: testing

#192 Added the documentation for django
  .gitignore
  README.md
Labels: documentation

#207 Exception handling for a csv file not containing a header
  Pipfile.lock
  gatorgrouper/tests/test_read_student_file.py
  gatorgrouper/utils/gatorgrouper.py
  gatorgrouper/utils/parse_arguments.py
  gatorgrouper/utils/read_student_file.py
Labels: bug, testing

#225 Django minimum viable product: upload CSV and pass data into grouping functions
  .pylintrc
  Pipfile
  Pipfile.lock
  gatorgrouper.py
  gatorgrouper/__init__.py
  gatorgrouper/forms.py
  gatorgrouper/templates/displaygroups.html
  gatorgrouper/templates/gatorgrouper/base.html
  gatorgrouper/templates/gatorgrouper/viewing-groups.html
  gatorgrouper/templates/upload.html
  gatorgrouper/tests/test_absent.py
  gatorgrouper/tests/test_arguments.py
  gatorgrouper/tests/test_create_escaped_string.py
  gatorgrouper/tests/test_display.py
  gatorgrouper/tests/test_group_method.py
  gatorgrouper/tests/test_group_size.py
  gatorgrouper/tests/test_num_group.py
  gatorgrouper/tests/test_read_student_file.py
  gatorgrouper/urls.py
  gatorgrouper/utils/group_random.py
  gatorgrouper/utils/group_rrobin.py
  gatorgrouper/utils/myscript.py
  gatorgrouper/utils/parse_arguments.py
  gatorgrouper/views.py
Labels: enhancement, priority, product

#218 Update to .gitignore to reflect additions
  .gitignore
Labels: enhancement

#226 CLI Minimum Viable Product: Fix All Existing Bugs and Provide Some Working Grouping Algorithms
  .travis.yml
  Pipfile.lock
  gatorgrouper.py
  gatorgrouper/tests/conftest.py
  gatorgrouper/tests/test_arguments.py
  gatorgrouper/tests/test_group_size.py
  gatorgrouper/tests/test_num_group.py
  gatorgrouper/tests/test_read_student_file.py
  gatorgrouper/utils/constants.py
  gatorgrouper/utils/defaults.py
  gatorgrouper/utils/parse_arguments.py
  gatorgrouper/utils/read_student_file.py
  gatorgrouper_cli.py
  manage.py
  pytest.cov
  tests/__init__.py
  tests/conftest.py
  tests/test_absent.py
  tests/test_admin.py
  tests/test_arguments.py
  tests/test_create_escaped_string.py
  tests/test_display.py
  tests/test_group_method.py
  tests/test_models.py
  tests/test_read_student_file.py
  tests/test_urls.py
  tests/test_views.py
Labels: bug, design, enhancement, product, refactor, testing

#216 Mutation testing with mutmut
  .mutmut-cache
  Pipfile
  Pipfile.lock
  setup.cfg
Labels: enhancement, testing, tools

#236 Edited the README.md for New Parse Argument
  README.md
Labels: documentation

#240 Implement Graph Algorithm Grouping Method with CLI
  Pipfile.lock
  gatorgrouper/utils/constants.py
  gatorgrouper/utils/group_graph.py
  gatorgrouper/utils/parse_arguments.py
  gatorgrouper/utils/read_student_file.py
  gatorgrouper_cli.py
  tests/conftest.py
  tests/test_read_student_file.py
Labels: design, enhancement, priority

#248 Homepage upgrade
  gatorgrouper/static/gatorgrouper/css/main.css
  gatorgrouper/templates/gatorgrouper/home.html
Labels: interface, need-feedback

#261 Test Case, Documentation, Refactoring for `group_graph.py`
  README.md
  gatorgrouper/utils/constants.py
  gatorgrouper/utils/group_graph.py
  gatorgrouper/utils/parse_arguments.py
  gatorgrouper/utils/read_student_file.py
  gatorgrouper_cli.py
  tests/conftest.py
  tests/test_group_graph.py
  tests/test_read_student_file.py
Labels: bug, documentation, refactor, testing

#269 Command line interface method
  gatorgrouper/utils/constants.py
  gatorgrouper/utils/parse_arguments.py
  gatorgrouper/utils/run.py
  gatorgrouper_cli.py
  tests/conftest.py
  tests/test_run.py
Labels: bug, refactor, testing

#273 Quickfix/Duplicate Rrobin Method
  gatorgrouper/utils/group_rrobin.py
  gatorgrouper/views.py
Labels: bug

#281 QuickFix/skipped valid form test in `test_forms.py`
  gatorgrouper/forms.py
  tests/test_forms.py
Labels: bug, testing

#278 Generalize interface for Both CLI and WI
  gatorgrouper/utils/group_creation.py
  gatorgrouper/utils/run.py
  gatorgrouper/views.py
  tests/test_run.py
Labels: bug, enhancement, interface, refactor, testing

#289 Feature/group detail view
  gatorgrouper/static/gatorgrouper/css/main.css
  gatorgrouper/templates/gatorgrouper/assignment_detail.html
  gatorgrouper/templates/gatorgrouper/base.html
  gatorgrouper/templates/gatorgrouper/profile.html
  gatorgrouper/templates/gatorgrouper/viewing-groups.html
  gatorgrouper/urls.py
  gatorgrouper/views.py
  tests/test_urls.py
  tests/test_views.py
Labels: design, enhancement, refactor, technique, testing
